//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FISWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attent
    {
        public string log_id { get; set; }
        public string attent_user { get; set; }
        public System.DateTime attent_time { get; set; }
        public string attent_device { get; set; }
        public int attent_type { get; set; }
        public string description { get; set; }
    
        public virtual User User { get; set; }
        public virtual Device Device { get; set; }
    }
}
