//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FISWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public string pos_id { get; set; }
        public string pos_displayed { get; set; }
        public byte pos_type { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
