//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FISWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Attents = new HashSet<Attent>();
            this.Devices = new HashSet<Device>();
            this.Positions = new HashSet<Position>();
        }
    
        public string user_id { get; set; }
        public string password { get; set; }
        public int status { get; set; }
        public int user_type { get; set; }
        public string full_name { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string address { get; set; }
        public string pos_id { get; set; }
        public string department { get; set; }
        public string phone { get; set; }
        public string avatar { get; set; }
        public string finger_image { get; set; }
        public string finger_vector { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attent> Attents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position> Positions { get; set; }
        public virtual Position Position { get; set; }
    }
}
